version: '2'
services:
  api-gateway:
    build: ./
    volumes:
      - ./:/usr/local/src/microservices-api-gateway/
      - /mnt/cloud/operacoes/:/operacoes/
    ports:
      - localhost:8888:7777
    environment:
      - PORT=7777
      - BASEPATH=/operacoes/
    command: ./node_modules/.bin/nodemon app.js

